# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
    [
        {id: 0,  size: 0.008},
        {id: 1,  size: 0.008},
        {id: 2,  size: 0.008},
        {id: 3,  size: 0.008},
        {id: 4,  size: 0.008},
        {id: 5,  size: 0.008},
        {id: 6,  size: 0.008},
        {id: 7,  size: 0.008},
        {id: 8,  size: 0.008},
        {id: 9,  size: 0.008},
        {id: 10, size: 0.008},
        {id: 11, size: 0.008},
        {id: 12, size: 0.008},
        {id: 13, size: 0.008},
        {id: 14, size: 0.008},
        {id: 15, size: 0.008},
        {id: 16, size: 0.008},
        {id: 17, size: 0.008},
        {id: 18, size: 0.008},
        {id: 19, size: 0.008},
        {id: 20, size: 0.008},
        {id: 21, size: 0.008},
        {id: 22, size: 0.008},
        {id: 23, size: 0.008},
        {id: 24, size: 0.008},
        {id: 25, size: 0.008},
        {id: 26, size: 0.008},
        {id: 27, size: 0.008},
        {id: 28, size: 0.008},
        {id: 29, size: 0.008},
        {id: 30, size: 0.008},
        {id: 31, size: 0.008},
        {id: 32, size: 0.008},
        {id: 33, size: 0.008},
        {id: 34, size: 0.008},
        {id: 35, size: 0.008},
        {id: 36, size: 0.008},
        {id: 37, size: 0.008},
        {id: 38, size: 0.008},
        {id: 39, size: 0.008},
        {id: 40, size: 0.008},
        {id: 41, size: 0.008},
        {id: 42, size: 0.008},
        {id: 43, size: 0.008},
        {id: 44, size: 0.008},
        {id: 45, size: 0.008},
        {id: 46, size: 0.008},
        {id: 47, size: 0.008},
        {id: 48, size: 0.008},
        {id: 49, size: 0.008},
        {id: 50, size: 0.008},
        {id: 51, size: 0.008},
        {id: 52, size: 0.008},
        {id: 53, size: 0.008},
        {id: 54, size: 0.008},
        {id: 55, size: 0.008},
        {id: 56, size: 0.008},
        {id: 57, size: 0.008},
        {id: 58, size: 0.008},
        {id: 59, size: 0.008},
        {id: 60, size: 0.008},
        {id: 61, size: 0.008},
        {id: 62, size: 0.008},
        {id: 63, size: 0.008},
        {id: 64, size: 0.008},
        {id: 65, size: 0.008},
        {id: 66, size: 0.008},
        {id: 67, size: 0.008},
        {id: 68, size: 0.008},
        {id: 69, size: 0.008},
        {id: 70, size: 0.008},
        {id: 71, size: 0.008},
        {id: 72, size: 0.008},
        {id: 73, size: 0.008},
        {id: 74, size: 0.008},
        {id: 75, size: 0.008},
        {id: 76, size: 0.008},
        {id: 77, size: 0.008},
        {id: 78, size: 0.008},
        {id: 79, size: 0.008},
        {id: 80, size: 0.008},
        {id: 81, size: 0.008},
        {id: 82, size: 0.008},
        {id: 83, size: 0.008},
        {id: 84, size: 0.008},
        {id: 85, size: 0.008},
        {id: 86, size: 0.008},
        {id: 87, size: 0.008},
        {id: 88, size: 0.008},
        {id: 89, size: 0.008},
        {id: 90, size: 0.008},
        {id: 91, size: 0.008},
        {id: 92, size: 0.008},
        {id: 93, size: 0.008},
        {id: 94, size: 0.008},
        {id: 95, size: 0.008},
        {id: 96, size: 0.008},
        {id: 97, size: 0.008},
        {id: 98, size: 0.008},
        {id: 99, size: 0.008},
        {id: 100, size: 0.008},
        {id: 101, size: 0.008},
        {id: 102, size: 0.008},
        {id: 103, size: 0.008},
        {id: 104, size: 0.008},
        {id: 105, size: 0.008},
        {id: 106, size: 0.008},
        {id: 107, size: 0.008},
        {id: 108, size: 0.008},
        {id: 109, size: 0.008},
        {id: 110, size: 0.008},
        {id: 111, size: 0.008},
        {id: 112, size: 0.008},
        {id: 113, size: 0.008},
        {id: 114, size: 0.008},
        {id: 115, size: 0.008},
        {id: 116, size: 0.008},
        {id: 117, size: 0.008},
        {id: 118, size: 0.008},
        {id: 119, size: 0.008},
        {id: 120, size: 0.008},
        {id: 121, size: 0.008},
        {id: 122, size: 0.008},
        {id: 123, size: 0.008},
        {id: 124, size: 0.008},
        {id: 125, size: 0.008},
        {id: 126, size: 0.008},
        {id: 127, size: 0.008},
        {id: 128, size: 0.008},
        {id: 129, size: 0.008},
        {id: 130, size: 0.008},
        {id: 131, size: 0.008},
        {id: 132, size: 0.008},
        {id: 133, size: 0.008},
        {id: 134, size: 0.008},
        {id: 135, size: 0.008},
        {id: 136, size: 0.008},
        {id: 137, size: 0.008},
        {id: 138, size: 0.008},
        {id: 139, size: 0.008},
        {id: 140, size: 0.008},
        {id: 141, size: 0.008},
        {id: 142, size: 0.008},
        {id: 143, size: 0.008},
        {id: 144, size: 0.008},
        {id: 145, size: 0.008},
        {id: 146, size: 0.008},
        {id: 147, size: 0.008},
        {id: 148, size: 0.008},
        {id: 149, size: 0.008},
        {id: 150, size: 0.008},
        {id: 151, size: 0.008},
        {id: 152, size: 0.008},
        {id: 153, size: 0.008},
        {id: 154, size: 0.008},
        {id: 155, size: 0.008},
        {id: 156, size: 0.008},
        {id: 157, size: 0.008},
        {id: 158, size: 0.008},
        {id: 159, size: 0.008}
    ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
#tag_bundles:
#  [
      #    {
      #      name: 'bundle1',
      #      layout:
      #        [
      #          {id: 0,  size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 1,  size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 2,  size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 3,  size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 4,  size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 5,  size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 6,  size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 7,  size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 8,  size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 9,  size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 10, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 11, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 12, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 13, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 14, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 15, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
      #        ]
      #    },
      #    {
      #      name: 'bundle2',
      #      layout:
      #        [
      #          {id: 16, size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 17, size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 18, size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 19, size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 20, size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 21, size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 22, size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 23, size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 24, size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 25, size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 26, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 27, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 28, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 29, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 30, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
      #          {id: 31, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
      #        ]
      #    }
      #  ]

      #tag_bundles:
      #  [
      #    {
      #      name: 'my_bundle',
      #      layout:
      #        [
      #          {id: 0, size: 0.04, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
      #          {id: 7, size: 0.04, x: 0.1733, y: -0.0650, z: 0.0054, qw: 0.9911, qx: 0.0890, qy: 0.0985, qz: 0.0069},
      #          {id: 10, size: 0.04, x: 0.1344, y: -0.1232, z: 0.0234, qw: 0.9951, qx: 0.0623, qy: 0.0760, qz: -0.0051},
      #          {id: 6, size: 0.04, x: 0.1301, y: -0.0708, z: 0.0226, qw: 0.9958, qx: 0.0488, qy: 0.0774, qz: 0.0052},
      #          {id: 5, size: 0.04, x: 0.0746, y: -0.0666, z: 0.0210, qw: 0.9983, qx: 0.0423, qy: 0.0385, qz: -0.0066},
      #          {id: 4, size: 0.04, x: 0.0097, y: -0.0561, z: 0.0076, qw: 0.9986, qx: 0.0472, qy: -0.0034, qz: -0.0234},
      #          {id: 3, size: 0.04, x: 0.1559, y: 0.0015, z: -0.0144, qw: 0.9837, qx: 0.0407, qy: 0.1685, qz: 0.0483},
      #          {id: 2, size: 0.04, x: 0.1130, y: -0.0077, z: 0.0053, qw: 0.9940, qx: 0.0142, qy: 0.1045, qz: 0.0297},
      #          {id: 1, size: 0.04, x: 0.0628, y: -0.0089, z: 0.0110, qw: 0.9989, qx: 0.0007, qy: 0.0430, qz: 0.0166},
      #          {id: 11, size: 0.04, x: 0.1834, y: -0.1231, z: 0.0164, qw: 0.9970, qx: 0.0572, qy: 0.0531, qz: -0.0009},
      #          {id: 13, size: 0.04, x: 0.0618, y: -0.1620, z: -0.0028, qw: 0.9856, qx: 0.1414, qy: 0.0773, qz: -0.0511},
      #          {id: 12, size: 0.04, x: -0.0023, y: -0.1527, z: -0.0128, qw: 0.9866, qx: 0.1459, qy: 0.0160, qz: -0.0708},
      #          {id: 14, size: 0.04, x: 0.1197, y: -0.1666, z: -0.0017, qw: 0.9881, qx: 0.0676, qy: 0.1379, qz: -0.0055},
      #          {id: 8, size: 0.04, x: 0.0105, y: -0.1070, z: 0.0049, qw: 0.9951, qx: 0.0864, qy: -0.0034, qz: -0.0487},
      #          {id: 9, size: 0.04, x: 0.0755, y: -0.1172, z: 0.0180, qw: 0.9950, qx: 0.0824, qy: 0.0498, qz: -0.0265},
      #          {id: 15, size: 0.04, x: 0.1765, y: -0.1685, z: 0.0006, qw: 0.9961, qx: -0.0251, qy: 0.0824, qz: 0.0177}
      #        ]
      #    }
      #  ]

      #tag_bundles:
      #  [
      #    {
      #      name: 'my_bundle',
      #      layout:
      #        [
      #          {id: 0, size: 0.04, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
      #          {id: 12, size: 0.04, x: -0.0037, y: -0.1498, z: 0.0297, qw: 0.9903, qx: -0.0804, qy: -0.1132, qz: -0.0021},
      #          {id: 3, size: 0.04, x: 0.1419, y: -0.0037, z: 0.0301, qw: 0.9958, qx: -0.0820, qy: -0.0407, qz: -0.0064},
      #          {id: 4, size: 0.04, x: -0.0017, y: -0.0511, z: 0.0134, qw: 0.9981, qx: -0.0142, qy: 0.0591, qz: -0.0029},
      #          {id: 2, size: 0.04, x: 0.0953, y: -0.0024, z: 0.0195, qw: 0.9975, qx: -0.0636, qy: -0.0293, qz: -0.0033},
      #          {id: 5, size: 0.04, x: 0.0459, y: -0.0519, z: 0.0205, qw: 0.9995, qx: -0.0329, qy: -0.0020, qz: -0.0028},
      #          {id: 6, size: 0.04, x: 0.0930, y: -0.0524, z: 0.0303, qw: 0.9980, qx: -0.0563, qy: -0.0299, qz: -0.0044},
      #          {id: 7, size: 0.04, x: 0.1402, y: -0.0532, z: 0.0393, qw: 0.9964, qx: -0.0738, qy: -0.0411, qz: -0.0089},
      #          {id: 13, size: 0.04, x: 0.0438, y: -0.1508, z: 0.0355, qw: 0.9910, qx: -0.1299, qy: 0.0213, qz: -0.0235},
      #          {id: 8, size: 0.04, x: -0.0033, y: -0.1007, z: 0.0232, qw: 0.9870, qx: -0.0159, qy: -0.1599, qz: -0.0003},
      #          {id: 11, size: 0.04, x: 0.1379, y: -0.1024, z: 0.0482, qw: 0.9971, qx: -0.0682, qy: -0.0309, qz: -0.0128},
      #          {id: 10, size: 0.04, x: 0.0905, y: -0.1018, z: 0.0406, qw: 0.9973, qx: -0.0701, qy: -0.0163, qz: -0.0117},
      #          {id: 9, size: 0.04, x: 0.0438, y: -0.1013, z: 0.0313, qw: 0.9971, qx: -0.0744, qy: 0.0128, qz: -0.0118},
      #          {id: 1, size: 0.04, x: 0.0477, y: -0.0014, z: 0.0107, qw: 0.9993, qx: -0.0302, qy: -0.0220, qz: -0.0003},
      #          {id: 15, size: 0.04, x: 0.1394, y: -0.1526, z: 0.0486, qw: 0.9957, qx: -0.0811, qy: -0.0413, qz: -0.0165},
      #          {id: 14, size: 0.04, x: 0.0915, y: -0.1518, z: 0.0416, qw: 0.9950, qx: -0.0949, qy: -0.0233, qz: -0.0186}
      #        ]
      #    }
      #  ]

tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          {id: 0, size: 0.04, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 7, size: 0.04, x: 0.1570, y: -0.0600, z: 0.0015, qw: 0.9995, qx: -0.0021, qy: 0.0152, qz: -0.0273},
          {id: 6, size: 0.04, x: 0.1103, y: -0.0671, z: 0.0130, qw: 0.9994, qx: -0.0143, qy: 0.0314, qz: -0.0041},
          {id: 5, size: 0.04, x: 0.0550, y: -0.0565, z: 0.0051, qw: 0.9993, qx: -0.0008, qy: 0.0367, qz: 0.0079},
          {id: 4, size: 0.04, x: -0.0123, y: -0.0330, z: -0.0172, qw: 0.9992, qx: 0.0301, qy: 0.0274, qz: 0.0062},
          {id: 3, size: 0.04, x: 0.1590, y: -0.0128, z: 0.0034, qw: 0.9988, qx: -0.0034, qy: 0.0478, qz: -0.0039},
          {id: 1, size: 0.04, x: 0.0603, y: -0.0174, z: 0.0142, qw: 0.9996, qx: -0.0141, qy: 0.0227, qz: 0.0058},
          {id: 2, size: 0.04, x: 0.1121, y: -0.0221, z: 0.0159, qw: 0.9992, qx: -0.0179, qy: 0.0369, qz: 0.0036},
          {id: 9, size: 0.04, x: 0.0419, y: -0.0852, z: -0.0187, qw: 0.9968, qx: -0.0074, qy: 0.0770, qz: 0.0210},
          {id: 11, size: 0.04, x: 0.1507, y: -0.0989, z: -0.0104, qw: 0.7639, qx: 0.6047, qy: 0.2239, qz: -0.0266},
          {id: 10, size: 0.04, x: 0.1034, y: -0.1025, z: -0.0007, qw: 0.9984, qx: -0.0420, qy: 0.0385, qz: 0.0000},
          {id: 8, size: 0.04, x: -0.0340, y: -0.0571, z: -0.0499, qw: 0.9957, qx: 0.0482, qy: 0.0768, qz: 0.0167},
          {id: 12, size: 0.04, x: -0.0645, y: -0.0755, z: -0.0981, qw: 0.9812, qx: 0.0332, qy: 0.1828, qz: 0.0518},
          {id: 14, size: 0.04, x: 0.0905, y: -0.1291, z: -0.0277, qw: 0.7614, qx: 0.5810, qy: 0.2830, qz: -0.0514},
          {id: 13, size: 0.04, x: 0.0231, y: -0.1087, z: -0.0544, qw: 0.8619, qx: 0.4163, qy: 0.2874, qz: -0.0353},
          {id: 15, size: 0.04, x: 0.1397, y: -0.1286, z: -0.0305, qw: 0.7954, qx: 0.5563, qy: 0.2378, qz: -0.0354}
        ]
    }
  ]
