# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
    [
    ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'bundle1',
      layout:
        [
          {id: 0,  size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 1,  size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 2,  size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 3,  size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 4,  size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 5,  size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 6,  size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 7,  size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 8,  size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 9,  size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 10, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 11, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 12, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 13, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 14, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 15, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    #{
    #  name: 'bundle2',
    #  layout:
    #    [
    #      {id: 16, size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 17, size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 18, size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 19, size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 20, size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 21, size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 22, size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 23, size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 24, size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 25, size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 26, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 27, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 28, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 29, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 30, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
    #      {id: 31, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
    #    ]
    #}
  ]


      #tag_bundles:
      #  [
      #    {
      #      name: 'my_bundle',
      #      layout:
      #        [
      #          {id: 0, size: 0.04, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
      #          {id: 7, size: 0.04, x: 0.1570, y: -0.0600, z: 0.0015, qw: 0.9995, qx: -0.0021, qy: 0.0152, qz: -0.0273},
      #          {id: 6, size: 0.04, x: 0.1103, y: -0.0671, z: 0.0130, qw: 0.9994, qx: -0.0143, qy: 0.0314, qz: -0.0041},
      #          {id: 5, size: 0.04, x: 0.0550, y: -0.0565, z: 0.0051, qw: 0.9993, qx: -0.0008, qy: 0.0367, qz: 0.0079},
      #          {id: 4, size: 0.04, x: -0.0123, y: -0.0330, z: -0.0172, qw: 0.9992, qx: 0.0301, qy: 0.0274, qz: 0.0062},
      #          {id: 3, size: 0.04, x: 0.1590, y: -0.0128, z: 0.0034, qw: 0.9988, qx: -0.0034, qy: 0.0478, qz: -0.0039},
      #          {id: 1, size: 0.04, x: 0.0603, y: -0.0174, z: 0.0142, qw: 0.9996, qx: -0.0141, qy: 0.0227, qz: 0.0058},
      #          {id: 2, size: 0.04, x: 0.1121, y: -0.0221, z: 0.0159, qw: 0.9992, qx: -0.0179, qy: 0.0369, qz: 0.0036},
      #          {id: 9, size: 0.04, x: 0.0419, y: -0.0852, z: -0.0187, qw: 0.9968, qx: -0.0074, qy: 0.0770, qz: 0.0210},
      #          {id: 11, size: 0.04, x: 0.1507, y: -0.0989, z: -0.0104, qw: 0.7639, qx: 0.6047, qy: 0.2239, qz: -0.0266},
      #          {id: 10, size: 0.04, x: 0.1034, y: -0.1025, z: -0.0007, qw: 0.9984, qx: -0.0420, qy: 0.0385, qz: 0.0000},
      #          {id: 8, size: 0.04, x: -0.0340, y: -0.0571, z: -0.0499, qw: 0.9957, qx: 0.0482, qy: 0.0768, qz: 0.0167},
      #          {id: 12, size: 0.04, x: -0.0645, y: -0.0755, z: -0.0981, qw: 0.9812, qx: 0.0332, qy: 0.1828, qz: 0.0518},
      #          {id: 14, size: 0.04, x: 0.0905, y: -0.1291, z: -0.0277, qw: 0.7614, qx: 0.5810, qy: 0.2830, qz: -0.0514},
      #          {id: 13, size: 0.04, x: 0.0231, y: -0.1087, z: -0.0544, qw: 0.8619, qx: 0.4163, qy: 0.2874, qz: -0.0353},
      #          {id: 15, size: 0.04, x: 0.1397, y: -0.1286, z: -0.0305, qw: 0.7954, qx: 0.5563, qy: 0.2378, qz: -0.0354}
      #        ]
      #    }
      #  ]



