# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
    [
        #      {id:  0, size: 0.12},
        #      {id:  1, size: 0.12},
        #      {id:  2, size: 0.12},
        #      {id:  3, size: 0.12},
        #      {id:  4, size: 0.12},
        #      {id:  5, size: 0.12},
        #      {id:  6, size: 0.12},
        #      {id:  7, size: 0.12},
        #      {id:  8, size: 0.12},
        #      {id:  9, size: 0.12},
        #      {id: 10, size: 0.12},
        #      {id: 11, size: 0.12},
        #      {id: 12, size: 0.12},
        #      {id: 13, size: 0.12},
        #      {id: 14, size: 0.12},
        #      {id: 15, size: 0.12},
        #      {id: 16, size: 0.12},
        #      {id: 17, size: 0.12},
        #      {id: 18, size: 0.12},
        #      {id: 19, size: 0.12},
        #      {id: 20, size: 0.12},
        #      {id: 21, size: 0.12},
        #      {id: 22, size: 0.12},
        #      {id: 23, size: 0.12},
        #      {id: 24, size: 0.12},
        #      {id: 25, size: 0.12},
        #      {id: 26, size: 0.12},
        #      {id: 27, size: 0.12},
        #      {id: 28, size: 0.12},
        #      {id: 29, size: 0.12},
        #      {id: 30, size: 0.12},
        #      {id: 31, size: 0.12},
        #      {id: 32, size: 0.12},
        #      {id: 33, size: 0.12},
        #      {id: 34, size: 0.12},
        #      {id: 35, size: 0.12}
    ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'bundle1',
      layout:
        [
          {id: 0,  size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 1,  size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 2,  size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 3,  size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 4,  size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 5,  size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 6,  size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 7,  size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 8,  size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 9,  size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 10, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 11, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 12, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 13, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 14, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 15, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle2',
      layout:
        [
          {id: 16, size: 0.0382, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 17, size: 0.0382, x: 0.0000, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 18, size: 0.0382, x: 0.0000, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 19, size: 0.0382, x: 0.0000, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 20, size: 0.0382, x: 0.0494, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 21, size: 0.0382, x: 0.0494, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 22, size: 0.0382, x: 0.0494, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 23, size: 0.0382, x: 0.0494, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 24, size: 0.0382, x: 0.0988, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 25, size: 0.0382, x: 0.0988, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 26, size: 0.0382, x: 0.0988, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 27, size: 0.0382, x: 0.0988, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 28, size: 0.0382, x: 0.1482, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 29, size: 0.0382, x: 0.1482, y: 0.0494, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 30, size: 0.0382, x: 0.1482, y: 0.0988, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 31, size: 0.0382, x: 0.1482, y: 0.1482, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    }
  ]
